const cartKey = 'atandra-cart';
const money = (value) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value);
const getCart = () => JSON.parse(localStorage.getItem(cartKey) || '[]');
const setCart = (cart) => { localStorage.setItem(cartKey, JSON.stringify(cart)); updateCartCount(); };
const updateCartCount = () => { const node = document.querySelector('#cart-count'); if (node) node.textContent = getCart().reduce((total, item) => total + item.quantity, 0); };
const asset = (url) => url || '/img/fabric-hero.png';
async function api(path, options = {}) { const response = await fetch(`/api${path}`, { credentials: 'include', ...options }); const data = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(data?.error || 'Request gagal'); return data; }
function addCart(item) { const cart = getCart(); const found = cart.find((entry) => entry.variant_id === item.variant_id); if (found) found.quantity += item.quantity; else cart.push(item); setCart(cart); alert('Kain ditambahkan ke keranjang.'); }
function categoryFor(gsm) { return gsm <= 135 ? 'light' : gsm <= 160 ? 'medium' : 'structured'; }
function productCard(product) { return `<article class="shop-card"><a href="/product.html?slug=${product.slug}"><img src="${asset(product.image)}" alt="${product.name}" loading="lazy"></a><div class="shop-card-body"><span class="eyebrow">${product.gsm} GSM · ${product.category_name}</span><h2>${product.name}</h2><p>${product.recommended_usage}</p><div class="shop-meta"><span>${product.width}</span><span>${product.available_stock} tersedia</span></div><div class="shop-card-actions"><b class="price">Mulai ${money(825000 + product.gsm * 1000)}</b><a class="shop-btn" href="/product.html?slug=${product.slug}">Lihat detail</a></div></div></article>`; }
async function initShop() { updateCartCount(); const grid = document.querySelector('#shop-grid'); let products = []; let active = 'all'; const render = () => { const query = document.querySelector('#search').value.toLowerCase(); const visible = products.filter((product) => (active === 'all' || categoryFor(product.gsm) === active) && `${product.name} ${product.sku} ${product.material}`.toLowerCase().includes(query)); grid.innerHTML = visible.length ? visible.map(productCard).join('') : '<div class="empty">Produk tidak ditemukan.</div>'; }; try { products = (await api('/products')).products; render(); } catch (error) { grid.innerHTML = `<div class="empty">${error.message}</div>`; } document.querySelector('#search').addEventListener('input', render); document.querySelectorAll('[data-filter]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('[data-filter]').forEach((item) => item.classList.remove('active')); button.classList.add('active'); active = button.dataset.filter; render(); })); }
async function initProduct() { updateCartCount(); const root = document.querySelector('#product-page'); try { const slug = new URLSearchParams(location.search).get('slug'); const { product } = await api(`/products/${slug}`); let selected = product.variants[0]; root.innerHTML = `<div class="product-layout"><img src="${asset(product.image)}" alt="${product.name}"><section class="product-info"><div class="eyebrow">${product.sku}</div><h1>${product.name}</h1><p>${product.description}</p><div class="spec-grid"><div><small>GRAMASI</small><b>${product.gsm} g/m²</b></div><div><small>LEBAR</small><b>${product.width}</b></div><div><small>BERAT</small><b>${product.weight_per_yard}</b></div></div><p class="eyebrow">Pilih warna</p><div class="color-list">${product.variants.map((variant, index) => `<button class="color-btn ${index === 0 ? 'active' : ''}" data-variant="${variant.id}">${variant.color}</button>`).join('')}</div><div class="qty"><label>Jumlah roll</label><input id="quantity" type="number" min="${product.moq}" value="${product.moq}"></div><button class="primary-btn" id="add">Tambah ke keranjang · ${money(selected.price)}</button><div class="notice">Stok tersedia: <b id="stock">${selected.available_stock} roll</b>.</div></section></div>`; document.querySelectorAll('[data-variant]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('[data-variant]').forEach((item) => item.classList.remove('active')); button.classList.add('active'); selected = product.variants.find((variant) => variant.id === Number(button.dataset.variant)); document.querySelector('#add').textContent = `Tambah ke keranjang · ${money(selected.price)}`; document.querySelector('#stock').textContent = `${selected.available_stock} roll`; })); document.querySelector('#add').addEventListener('click', () => addCart({ variant_id: selected.id, quantity: Number(document.querySelector('#quantity').value), product_name: product.name, variant_name: `${product.name} — ${selected.color}`, price: selected.price, image: product.image })); } catch (error) { root.innerHTML = `<div class="empty">${error.message}</div>`; } }
function renderCart() { const cart = getCart(); const list = document.querySelector('#cart-list'); if (!list) return; if (!cart.length) { list.innerHTML = '<p class="empty">Keranjang masih kosong.</p>'; return; } list.innerHTML = cart.map((item) => `<div class="cart-row"><img src="${asset(item.image)}"><div><b>${item.product_name}</b><small>${item.variant_name} · ${item.quantity} roll</small><strong>${money(item.price * item.quantity)}</strong></div></div>`).join(''); const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0); document.querySelector('#subtotal').textContent = money(subtotal); document.querySelector('#total').textContent = money(subtotal + 35000); }
async function initCheckout() { updateCartCount(); renderCart(); document.querySelector('#checkout-form').addEventListener('submit', async (event) => { event.preventDefault(); const message = document.querySelector('#checkout-message'); const values = Object.fromEntries(new FormData(event.currentTarget)); try { const result = await api('/orders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ customer: values, address: values, notes: values.notes, items: getCart().map((item) => ({ variant_id: item.variant_id, quantity: Number(item.quantity) })) }) }); message.hidden = false; message.textContent = `Pesanan ${result.orderNumber} berhasil dibuat. Status pembayaran: pending.`; localStorage.removeItem(cartKey); updateCartCount(); renderCart(); } catch (error) { message.hidden = false; message.textContent = error.message; } }); }
async function loadAdminDashboard() { const [dashboard, orders] = await Promise.all([api('/admin/dashboard'), api('/admin/orders')]); document.querySelector('#admin-auth').hidden = true; document.querySelector('#admin-dashboard').hidden = false; document.querySelector('#metrics').innerHTML = [['Penjualan', money(dashboard.sales)], ['Orders', dashboard.orders], ['Pending payment', dashboard.pendingPayments], ['Low stock', dashboard.lowStock]].map(([label, value]) => `<div class="metric"><small>${label}</small><strong>${value}</strong></div>`).join(''); document.querySelector('#orders').innerHTML = orders.orders.map((order) => `<tr><td>${order.order_number}</td><td>${order.customer_name || '-'}</td><td>${money(order.total)}</td><td class="status">${order.status}</td><td>${order.payment_status}</td></tr>`).join('') || '<tr><td colspan="5">Belum ada order.</td></tr>'; }
async function initAdmin() { const message = document.querySelector('#admin-auth-message'); const show = (text) => { message.hidden = false; message.textContent = text; }; try { await api('/auth/me'); await loadAdminDashboard(); } catch { document.querySelector('#admin-auth').hidden = false; } document.querySelector('#admin-login').addEventListener('click', async () => { try { await api('/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: document.querySelector('#admin-email').value, password: document.querySelector('#admin-password').value }) }); await loadAdminDashboard(); } catch (error) { show(error.message); } }); document.querySelector('#admin-register').addEventListener('click', async () => { try { await api('/auth/admin-register', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: document.querySelector('#admin-name').value, email: document.querySelector('#admin-email').value, password: document.querySelector('#admin-password').value, invite_key: document.querySelector('#admin-invite').value }) }); await loadAdminDashboard(); } catch (error) { show(error.message); } }); document.querySelector('#admin-logout').addEventListener('click', async () => { await api('/auth/logout', { method: 'POST' }); location.reload(); }); }
if (document.body.classList.contains('admin')) document.querySelectorAll('.admin-side a').forEach((link) => { if (link.textContent.trim() === 'Products') link.href = '/admin-products.html'; });
window.initShop = initShop; window.initProduct = initProduct; window.initCheckout = initCheckout; window.initAdmin = initAdmin; updateCartCount();
