const cartKey = 'atandra-cart';
const money = (value) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value);
// Escape teks sebelum dimasukkan ke innerHTML. Wajib untuk semua data yang
// berasal dari input user (nama customer, catatan, alamat) supaya tidak XSS.
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const getCart = () => JSON.parse(localStorage.getItem(cartKey) || '[]');
const setCart = (cart) => { localStorage.setItem(cartKey, JSON.stringify(cart)); updateCartCount(); };
const updateCartCount = () => { const node = document.querySelector('#cart-count'); if (node) node.textContent = getCart().reduce((total, item) => total + item.quantity, 0); };
const asset = (url) => url || '/img/fabric-hero.png';
async function api(path, options = {}) { const response = await fetch(`/api${path}`, { credentials: 'include', ...options }); const data = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(data?.error || 'Request gagal'); return data; }
function addCart(item) { const cart = getCart(); const found = cart.find((entry) => entry.variant_id === item.variant_id); if (found) found.quantity += item.quantity; else cart.push(item); setCart(cart); alert('Kain ditambahkan ke keranjang.'); }
function categoryFor(gsm) { return gsm <= 135 ? 'light' : gsm <= 160 ? 'medium' : 'structured'; }
function productCard(product) { return `<article class="shop-card"><a href="/produk?slug=${encodeURIComponent(product.slug)}"><img src="${esc(asset(product.image))}" alt="${esc(product.name)}" loading="lazy"></a><div class="shop-card-body"><span class="eyebrow">${esc(product.gsm)} GSM · ${esc(product.category_name)}</span><h2>${esc(product.name)}</h2><p>${esc(product.recommended_usage)}</p><div class="shop-meta"><span>${esc(product.width)}</span><span>${esc(product.available_stock)} tersedia</span></div><div class="shop-card-actions"><b class="price">Mulai ${money(825000 + product.gsm * 1000)}</b><a class="shop-btn" href="/produk?slug=${encodeURIComponent(product.slug)}">Lihat detail</a></div></div></article>`; }
async function initShop() { updateCartCount(); const grid = document.querySelector('#shop-grid'); let products = []; let active = 'all'; const render = () => { const query = document.querySelector('#search').value.toLowerCase(); const visible = products.filter((product) => (active === 'all' || categoryFor(product.gsm) === active) && `${product.name} ${product.sku} ${product.material}`.toLowerCase().includes(query)); grid.innerHTML = visible.length ? visible.map(productCard).join('') : '<div class="empty">Produk tidak ditemukan.</div>'; }; try { products = (await api('/products')).products; render(); } catch (error) { grid.innerHTML = `<div class="empty">${esc(error.message)}</div>`; } document.querySelector('#search').addEventListener('input', render); document.querySelectorAll('[data-filter]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('[data-filter]').forEach((item) => item.classList.remove('active')); button.classList.add('active'); active = button.dataset.filter; render(); })); }
async function initProduct() { updateCartCount(); const root = document.querySelector('#product-page'); try { const slug = new URLSearchParams(location.search).get('slug'); const { product } = await api(`/products/${encodeURIComponent(slug)}`); let selected = product.variants[0]; root.innerHTML = `<div class="product-layout"><img src="${esc(asset(product.image))}" alt="${esc(product.name)}"><section class="product-info"><div class="eyebrow">${esc(product.sku)}</div><h1>${esc(product.name)}</h1><p>${esc(product.description)}</p><div class="spec-grid"><div><small>GRAMASI</small><b>${esc(product.gsm)} g/m²</b></div><div><small>LEBAR</small><b>${esc(product.width)}</b></div><div><small>BERAT</small><b>${esc(product.weight_per_yard)}</b></div></div><p class="eyebrow">Pilih warna</p><div class="color-list">${product.variants.map((variant, index) => `<button class="color-btn ${index === 0 ? 'active' : ''}" data-variant="${Number(variant.id)}">${esc(variant.color)}</button>`).join('')}</div><div class="qty"><label>Jumlah roll</label><input id="quantity" type="number" min="${Number(product.moq)}" value="${Number(product.moq)}"></div><button class="primary-btn" id="add">Tambah ke keranjang · ${money(selected.price)}</button><div class="notice">Stok tersedia: <b id="stock">${esc(selected.available_stock)} roll</b>.</div></section></div>`; document.querySelectorAll('[data-variant]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('[data-variant]').forEach((item) => item.classList.remove('active')); button.classList.add('active'); selected = product.variants.find((variant) => variant.id === Number(button.dataset.variant)); document.querySelector('#add').textContent = `Tambah ke keranjang · ${money(selected.price)}`; document.querySelector('#stock').textContent = `${selected.available_stock} roll`; })); document.querySelector('#add').addEventListener('click', () => addCart({ variant_id: selected.id, quantity: Number(document.querySelector('#quantity').value), product_name: product.name, variant_name: `${product.name} — ${selected.color}`, price: selected.price, image: product.image })); } catch (error) { root.innerHTML = `<div class="empty">${esc(error.message)}</div>`; } }
function renderCart() { const cart = getCart(); const list = document.querySelector('#cart-list'); if (!list) return; if (!cart.length) { list.innerHTML = '<p class="empty">Keranjang masih kosong.</p>'; return; } list.innerHTML = cart.map((item) => `<div class="cart-row"><img src="${esc(asset(item.image))}"><div><b>${esc(item.product_name)}</b><small>${esc(item.variant_name)} · ${esc(item.quantity)} roll</small><strong>${money(item.price * item.quantity)}</strong></div></div>`).join(''); const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0); document.querySelector('#subtotal').textContent = money(subtotal); document.querySelector('#total').textContent = money(subtotal + 35000); }
async function initCheckout() { updateCartCount(); renderCart(); document.querySelector('#checkout-form').addEventListener('submit', async (event) => { event.preventDefault(); const message = document.querySelector('#checkout-message'); const values = Object.fromEntries(new FormData(event.currentTarget)); try { const result = await api('/orders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ customer: values, address: values, notes: values.notes, items: getCart().map((item) => ({ variant_id: item.variant_id, quantity: Number(item.quantity) })) }) }); message.hidden = false; message.textContent = `Pesanan ${result.orderNumber} berhasil dibuat. Status pembayaran: pending.`; localStorage.removeItem(cartKey); updateCartCount(); renderCart(); } catch (error) { message.hidden = false; message.textContent = error.message; } }); }
// Label status — dipakai dashboard. Sumber kebenaran transisi ada di admin-orders.js.
const ORDER_STATUS_LABEL = { pending_payment: 'Menunggu bayar', paid: 'Dibayar', processing: 'Diproses', packed: 'Dikemas', shipped: 'Dikirim', completed: 'Selesai', cancelled: 'Dibatalkan', refunded: 'Dikembalikan' };
const PAYMENT_STATUS_LABEL = { pending: 'Menunggu', paid: 'Lunas', failed: 'Gagal', refunded: 'Dikembalikan', expired: 'Kedaluwarsa' };
const DASHBOARD_ROWS = 8;
async function loadAdminDashboard() {
  const [dashboard, orders] = await Promise.all([api('/admin/dashboard'), api('/admin/orders')]);
  document.querySelector('#admin-auth').hidden = true;
  document.querySelector('#admin-dashboard').hidden = false;
  const kpis = [
    ['Penjualan', money(dashboard.sales), 'di luar batal & belum bayar'],
    ['Total pesanan', dashboard.orders, 'sepanjang waktu'],
    ['Menunggu bayar', dashboard.pendingPayments, 'perlu ditindak'],
    ['Stok menipis', dashboard.lowStock?.length ?? 0, 'varian ≤ ambang'],
  ];
  document.querySelector('#metrics').innerHTML = kpis.map(([label, value, hint]) => `<div class="kpi"><small>${esc(label)}</small><strong>${esc(value)}</strong><span>${esc(hint)}</span></div>`).join('');
  const recent = orders.orders.slice(0, DASHBOARD_ROWS);
  document.querySelector('#orders').innerHTML = recent.map((order) => `<tr><td><b>${esc(order.order_number)}</b></td><td>${esc(order.customer_name || '—')}</td><td class="num">${esc(money(order.total))}</td><td><span class="badge badge--${esc(order.status)}">${esc(ORDER_STATUS_LABEL[order.status] || order.status)}</span></td><td>${esc(PAYMENT_STATUS_LABEL[order.payment_status] || order.payment_status || '—')}</td></tr>`).join('') || `<tr><td colspan="5"><div class="empty-state"><b>Belum ada pesanan</b>Pesanan yang masuk dari checkout akan muncul di sini.</div></td></tr>`;
}
async function initAdmin() { const message = document.querySelector('#admin-auth-message'); const show = (text) => { message.hidden = false; message.textContent = text; }; try { await api('/auth/me'); await loadAdminDashboard(); } catch { document.querySelector('#admin-auth').hidden = false; } document.querySelector('#admin-login').addEventListener('click', async () => { try { await api('/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: document.querySelector('#admin-email').value, password: document.querySelector('#admin-password').value }) }); await loadAdminDashboard(); } catch (error) { show(error.message); } }); document.querySelector('#admin-register').addEventListener('click', async () => { try { await api('/auth/admin-register', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: document.querySelector('#admin-name').value, email: document.querySelector('#admin-email').value, password: document.querySelector('#admin-password').value, invite_key: document.querySelector('#admin-invite').value }) }); await loadAdminDashboard(); } catch (error) { show(error.message); } }); document.querySelector('#admin-logout').addEventListener('click', async () => { await api('/auth/logout', { method: 'POST' }); location.reload(); }); }
window.initShop = initShop; window.initProduct = initProduct; window.initCheckout = initCheckout; window.initAdmin = initAdmin; updateCartCount();
